export const FETCH = 'FETCH_APIMIDDLE_AVOID_SAME'
export const FETCH_REQUEST = 'FETCH_REQUEST_APIMIDDLE_AVOID_SAME'
export const FETCH_SUCCESS = 'FETCH_SUCCESS_APIMIDDLE_AVOID_SAME'
export const FETCH_REJECT = 'FETCH_REJECT_APIMIDDLE_AVOID_SAME'
